### ISSUE TITLE
Enable port forwarding on ProtonVPN and transmission

### ISSUE THREAD

**Issue by sebdanielsson** [jordanpotter/docker-mods#1]
Hi! Thanks for reaching out in the linuxserver/docker-transmission repo!

I'm trying to open a port for Transmission which I run in a Docker container with your mod applied but I still get port status closed and it's configured with the same port as before.

Not sure where the problem lies.

My setup:

ProtonVPN wireguard config:

```
[Interface]
# Key for Transmission
# Bouncing = 2
# NetShield = 0
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = on
# VPN Accelerator = on
PrivateKey = *****
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
PublicKey = *****
AllowedIPs = 0.0.0.0/0
Endpoint = xxx.xxx.xxx.xxx:51820
```

And here's my docker-compose containing the wireguard and transmission services:

```
services:
  wireguard:
    image: linuxserver/wireguard:1.0.20210914-alpine
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wgnet:
        ipv4_address: 172.100.0.2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    ports:
      - 9091:9091
    volumes:
      - /lib/modules:/lib/modules
      - ./wg0.conf:/config/wg0.conf
    restart: always
  transmission:
    image: linuxserver/transmission:version-4.0.3-r2
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    env_file:
      - secrets.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - PEERPORT=60831
      - DOCKER_MODS="jordanpotter/docker-mods:transmission-nat-pmp"
    volumes:
      - transmission_data:/config
      - /chungus/downloads:/downloads
    restart: always

networks:
  wgnet:
    external: true

volumes:
  transmission_data:
    name: transmission_data
```
