### ISSUE TITLE
failed to add port mapping: recvfrom: connection refused

### ISSUE THREAD

**Issue by alexg-k** [jordanpotter/docker-mods#2]
I repeatedly get the error message `failed to add port mapping: read udp 127.0.0.1:54156->127.0.0.11:5351: recvfrom: connection refused` when using your docker-mod. Maybe by looking at my compose file and the error log, you can advice me where to look next. Thanks!

compose.yaml
```
services:
  wireguard:
    image: linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
        #- net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "9091:9091/tcp"
      - "9696:9696/tcp"
    volumes:
      - ./wg0.conf:/config/wg0.conf
      - /lib/modules:/lib/modules
    restart: unless-stopped
  
  transmission:
    image:  linuxserver/transmission:latest
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    environment:
      - DOCKER_MODS=jordanpotter/docker-mods:transmission-nat-pmp
      - PUID=1000
      - PGID=1000
    env_file:
      - ./transmission.env
    volumes:
      - config:/config
      - downloads:/downloads
      - watch:/watch
    restart: unless-stopped
```

And here are the error messages:
```
[...]
compose-transmission-wireguard-transmission-1  | [custom-init] No custom files found, skipping...
compose-transmission-wireguard-transmission-1  | 2023/08/12 10:54:41 failed to add port mapping: read udp 127.0.0.1:51591->127.0.0.11:5351: recvfrom: connection refused
compose-transmission-wireguard-transmission-1  | setsockopt IP_MULTICAST_IF: Address not available
compose-transmission-wireguard-transmission-1  | bind: Address not available
compose-transmission-wireguard-prowlarr-1      | [Info] Microsoft.Hosting.Lifetime: Application started. Press Ctrl+C to shut down. 
compose-transmission-wireguard-prowlarr-1      | [Info] Microsoft.Hosting.Lifetime: Hosting environment: Production 
compose-transmission-wireguard-prowlarr-1      | [Info] Microsoft.Hosting.Lifetime: Content root path: /app/prowlarr/bin 
compose-transmission-wireguard-prowlarr-1      | [ls.io-init] done.
compose-transmission-wireguard-transmission-1  | 2023/08/12 10:54:42 failed to add port mapping: read udp 127.0.0.1:53213->127.0.0.11:5351: recvfrom: connection refused
compose-transmission-wireguard-transmission-1  | Connection to localhost
compose-transmission-wireguard-transmission-1  |  (127.0.0.1) 9091 port [tcp/*] succeeded!
compose-transmission-wireguard-transmission-1  | [ls.io-init] done.
compose-transmission-wireguard-transmission-1  | [2023-08-12 10:54:42.894] ERR net.cc:318 Couldn't bind port 61932 on 10.2.0.2: Address not available (99) (net.cc:318)
compose-transmission-wireguard-transmission-1  | 2023/08/12 10:54:43 failed to add port mapping: read udp 127.0.0.1:49067->127.0.0.11:5351: recvfrom: connection refused
compose-transmission-wireguard-transmission-1  | 2023/08/12 10:54:44 failed to add port mapping: read udp 127.0.0.1:39823->127.0.0.11:5351: recvfrom: connection refused
compose-transmission-wireguard-transmission-1  | 2023/08/12 10:54:45 failed to add port mapping: read udp 127.0.0.1:35210->127.0.0.11:5351: recvfrom: connection refused
compose-transmission-wireguard-transmission-1  | 2023/08/12 10:54:46 failed to add port mapping: read udp 127.0.0.1:32914->127.0.0.11:5351: recvfrom: connection refused
compose-transmission-wireguard-transmission-1  | 2023/08/12 10:54:47 failed to add port mapping: read udp 127.0.0.1:45919->127.0.0.11:5351: recvfrom: connection refused
compose-transmission-wireguard-transmission-1  | 2023/08/12 10:54:48 failed to add port mapping: read udp 127.0.0.1:48531->127.0.0.11:5351: recvfrom: connection refused
compose-transmission-wireguard-transmission-1  | 2023/08/12 10:54:49 failed to add port mapping: read udp 127.0.0.1:54156->127.0.0.11:5351: recvfrom: connection refused
[...]
```
