### ISSUE TITLE
digest could not be fetched from registry-1.docker.io

### ISSUE THREAD

**Issue by sebdanielsson** [jordanpotter/docker-mods#4]
Since a couple of days I'm getting this error when starting transmission with your awesome docker mod. Any idea how to resolve it?

```sh
[mod-init] Running Docker Modification Logic
[mod-init] Adding jordanpotter/docker-mods:transmission-nat-pmp to container
[mod-init] (ERROR) jordanpotter/docker-mods:transmission-nat-pmp digest could not be fetched from registry-1.docker.io
```

I tested to use ghcr instead of not specifying a repo and got the same error:

```sh
[mod-init] Running Docker Modification Logic
[mod-init] Adding jordanpotter/docker-mods:transmission-nat-pmp to container
[mod-init] (ERROR) jordanpotter/docker-mods:transmission-nat-pmp digest could not be fetched from ghcr.io
```

I'm using this compose file:

```yaml
---
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard:version-1.0.20210914-r4
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wgnet:
        ipv4_address: 172.100.0.2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    ports:
      - 9091:9091
    volumes:
      - /lib/modules:/lib/modules
      - ./wg0.conf:/config/wg_confs/wg0.conf
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.monitor-only=true
  transmission:
    image: ghcr.io/linuxserver/transmission:version-4.0.5-r2
    container_name: transmission
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    env_file:
      - secrets.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - DOCKER_MODS=jordanpotter/docker-mods:transmission-nat-pmp-20240702121311
    volumes:
      - transmission_data:/config
      - /chungus/media/downloads:/downloads
    restart: unless-stopped

networks:
  wgnet:
    ipam:
      config:
        - subnet: 172.100.0.0/24
          ip_range: 172.100.0.0/24
          gateway: 172.100.0.1
    attachable: true

volumes:
  transmission_data:
    name: transmission_data
```
